# Generated by Django 4.0.4 on 2022-05-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EverytimeApp', '0005_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='comments',
            field=models.PositiveIntegerField(null=True, verbose_name='댓글수'),
        ),
    ]
