# Generated by Django 4.0.4 on 2022-05-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EverytimeApp', '0006_board_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='comments',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='댓글수'),
        ),
    ]
